### ISSUE TITLE
Container name regex syntax not spported

### ISSUE THREAD

**Issue by SecT0uch** [Cisco-Talos/clamav-documentation#20]
The syntax described here is not working on my side.

https://github.com/Cisco-Talos/clamav-documentation/blob/2ff82a0899b567c5dd0da079bd0e062c6ad3ef7f/src/manual/Signatures/ContainerMetadata.md?plain=1#L22-L23

ClamAV 0.104.2/26476/Wed Mar  9 10:23:07 2022

**Comment by micahsnyder** [comment]
If I'm honest, I think that's just poorly written documentation and isn't intended to be used as a regex. I think it's trying to show a wide range of types.  Internally it immediately converts the given type, like "CL_TYPE_CPIO_OLD" to an enum (integer) equivalent and stores it for later use.  There is no regex processing code.

Interestingly, this is related to something I want to add in the future.  I'd like to create a new option to replace "Container" and "Intermediates" that is simply "Filetypes" and would work something like this:
`Filetypes: (ZIP | RAR) > PDF`  to say "a PDF in a ZIP or a RAR"
`Filetypes: (ZIP | RAR) > (PDF | HTML)`  to say "a PDF or HTML file in a ZIP or a RAR"
`Filetypes: EML > ZIP > *`  to say "any file in a ZIP in an email"

🤞 some day!

**Comment by justinboss360** [comment]
Nice work @val-ms 
Kudos
